import * as presets from "./presets";
import type { BitBuiltInMaskName, BitMask } from "./types";

export const bitMasks: Record<BitBuiltInMaskName, BitMask> = {
  brl: presets.maskBRL,
  usd: presets.maskUSD,
  eur: presets.maskEUR,
  gbp: presets.maskGBP,
  jpy: presets.maskJPY,
  percent: presets.maskPercent,
  decimal: presets.maskDecimal,
  int: presets.maskInteger,
  integer: presets.maskInteger,
  cpf: presets.maskCPF,
  cnpj: presets.maskCNPJ,
  cpfCnpj: presets.maskCPFCNPJ,
  rg: presets.maskRG,
  cep: presets.maskCEP,
  cnh: presets.maskCNH,
  plate: presets.maskPlate,
  phone: presets.maskPhone,
  landline: presets.maskLandline,
  date: presets.maskDate,
  time: presets.maskTime,
  usPhone: presets.maskUSPhone,
  zipCode: presets.maskZipCode,
  dateUS: presets.maskDateUS,
  ssn: presets.maskSSN,
  cc: presets.maskCreditCard,
  cvv: presets.maskCVV,
  dateISO: presets.maskDateISO,
  ip: presets.maskIPv4,
  ipv6: presets.maskIPv6,
  mac: presets.maskMacAddress,
  color: presets.maskColorHex,
  iban: presets.maskIBAN,
};
