#!/bin/sh
set -e

HOOKS_DIR=".git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-commit"

if [ ! -d "$HOOKS_DIR" ]; then
  echo "Error: .git/hooks not found. Run this script from the project root."
  exit 1
fi

cat > "$HOOK_FILE" << 'EOF'
#!/bin/sh
# Auto-generated by scripts/setup-hooks.sh
# Regenerates bit-form-context.txt before each commit.

npm run bundle-ctx
git add bit-form-context.txt 2>/dev/null || true
EOF

chmod +x "$HOOK_FILE"
echo "pre-commit hook installed: regenerates bit-form-context.txt on every commit."
