name: Publish bit-form to NPM

on:
  push:
    tags:
      - "v*"

# AS DUAS PERMISSÕES CRUCIAIS:
permissions:
  contents: write # Para o GitHub criar a Release na página
  id-token: write # Para o NPM aceitar o Trusted Publishing

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Instalar dependências
        run: npm install

      - name: Rodar Testes
        run: npm test

      - name: Build do Projeto
        run: npm run build

      - name: Publicar no NPM (Sem Token!)
        run: npm publish

      - name: Criar GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
